# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 봉쥬루
email: "blingface@naver.com"
description: ""
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://kimbongjun.github.io" # The base hostname & protocol for your site
github: "https://github.com/kimbongjun"
comments: true
markdown: kramdown
kramdown:
	input: GFM
	syntax_hightlighter: rouge
permalink: pretty
paginate: 5

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap
  - jekyll-youtube

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Category
category_dir: category/

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext
